name = "personal"
type = "static"

account_id = "c34ecd28b0bb381db77c345c273546f8"
zone_id = "5e1e5e06fd4ae2e3fec967a2fea694bd"

[env.production]
target = "pages"
project = "personal"
pages_build_output_dir = "dist"  # 添加此字段指定构建输出目录